# Generated by Django 4.2.2 on 2023-06-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_enviosemails_destinatarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviosemails',
            name='resposta',
        ),
        migrations.AddField(
            model_name='enviosemails',
            name='quantidade_noticias',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
