# Generated by Django 4.2.2 on 2023-06-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_enviosemails_resposta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviosemails',
            name='quantidade_noticias',
            field=models.IntegerField(verbose_name='Quantidade de noticias'),
        ),
    ]
